### ISSUE TITLE
Not an issue per se, a suggestion

### ISSUE THREAD

**Issue by sktguha** [paulirish/break-on-access#11]
For debugging functions, chrome has a debug method
for ex- 

```ja
var analytics = {
  log : function(){
  }
}
debug(analytics.log)
```

Now on calling analytics.log(), the debugger stops inside the function
so for objects whose functions are being added to breakOn on read , maybe the debug construct can be used. However one issue with this is the user has to execute the breakonaccess script in the console itself, as the debug is part of command line API and hence is not available to snippets/bookmarklets etc. I could file a PR if the people like the idea

**Comment by paulirish** [comment]
actually... do you want to submit a PR that just adds a note at the bottom of the readme with this?


seems good

**Comment by sktguha** [comment]
@paulirish sure sir. I will do so right away :). btw I wanted to ask you something. can I have your email id ?

**Comment by paulirish** [comment]
paul dot irish at gmail

**Comment by sktguha** [comment]
I have sent you a mail sir @paulirish  , from sktguha@gmail.com
