### ISSUE TITLE
add this option to devTools

### ISSUE THREAD

**Issue by adardesign** [paulirish/break-on-access#13]
This is such a handy snippet!

Can this be ported to dev tools to set a breakpoint on cookie set/change/remove 
![cookie](https://cloud.githubusercontent.com/assets/23543/12683783/3e36aef0-c689-11e5-9e74-4363a37ac88f.png)

**Comment by morganrallen** [comment]
I did a super quick test and I was in fact able to override `document.cookie` with `Object.defineProperty` so for cookies at least it would be possible.

**Comment by morganrallen** [comment]
Oh, sorry I was in a hurry when I saw this. Probably? But this is the wrong place to be asking I think.

**Comment by paulirish** [comment]
this is upstream here: https://code.google.com/p/chromium/issues/detail?id=154804
see my latest comment
